# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 19:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basegame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_location', models.IntegerField(default=0)),
                ('y_location', models.IntegerField(default=0)),
                ('flagged', models.BooleanField(default=False)),
                ('mined', models.BooleanField(default=False)),
                ('value', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MinesweeperGame',
            fields=[
                ('basegame_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basegame.BaseGame')),
                ('started', models.DateTimeField(null=True)),
                ('board_size', models.IntegerField(default=10)),
                ('num_mines', models.IntegerField(default=10)),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), null=True, size=None)),
                ('visibility', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=None), null=True, size=None)),
                ('flagged', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=None), null=True, size=None)),
                ('status', models.IntegerField(default=0)),
            ],
            bases=('basegame.basegame',),
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('move_type', models.CharField(default='', max_length=10)),
                ('undone', models.BooleanField(default=False)),
                ('hidden_fields', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('flagged_fields', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('game_status', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minesweeper.MinesweeperGame')),
                ('selected_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minesweeper.Field')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='minesweeper.MinesweeperGame'),
        ),
    ]
